
DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  content VARCHAR(255) NOT NULL,
  date_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
